secrets:
    DATABASE_URL: "mysql://tosainu:AHdasfsdb124!$4212412WondergunPeePeePoo$@34.106.173.48:3306/tosainu"
    PURESTAKE_API_KEY: "N3UN7nc1Hc7U8GrYRMZDTazVNjffy2QA6voeuBxC"
    GOOGLE_CREDENTIALS: "MTZocnVzc2VsbDprXzQ3em1AOzdfLUEmXiUxODc="
